/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The city's grid.geojson (H3 res-9 polygons; properties h3, district_id, district_name, neighborhood, habitable, population_est; numeric feature id = row index). Static, cache it. Same file as data/processed/{city}/grid.geojson. */
        get: operations["getGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["score"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/place/{h3}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/commute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Travel minutes from every habitable res-9 cell to the res-8 cell that contains (lat, lon). Unreachable (>120 min) cells are omitted. */
        get: operations["getCommute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin units of the city (static info). For a ranking use POST /score with aggregate=district. */
        get: operations["listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/similar/{h3}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSimilar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/twins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Twin neighbourhoods across cities (distance similarity on the pooled cross-city feature vector: 1 − d / median random-pair distance, clipped to 0–1). Give either h3 or district. */
        get: operations["getTwins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Local, accent-insensitive address/POI/place search ("zizkov" → "Žižkov"); Photon fallback. */
        get: operations["geocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/live/air": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Nearest air-quality station (K: GIOŚ, P: ČHMÚ/Golemio). Cached ≥ 10 min. Never fails hard; status tells the story. */
        get: operations["getLiveAir"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/live/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description (P2) Live departures. K: ZTP GTFS-RT; P: Golemio departure boards. May return status=unavailable. */
        get: operations["getLiveDepartures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{city}/prefs/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description (P2) Pairs of contrasting place profiles for preference learning. */
        get: operations["getPrefPairs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prefs/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description (P2) Bradley–Terry logistic regression on criterion-difference vectors → suggested emoji levels. */
        post: operations["fitPrefs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @example unknown_city
                 * @example unknown_cell
                 * @example invalid_request
                 * @example unavailable
                 */
                code: string;
                message: string;
            };
        };
        /** @enum {string} */
        Lang: "pl" | "cs" | "en" | "ko";
        /** @enum {string} */
        CityId: "krakow" | "praha";
        /** @enum {string} */
        Currency: "PLN" | "CZK";
        /**
         * @default transit
         * @enum {string}
         */
        Mode: "transit" | "bike" | "walk";
        Level: number;
        /** @example 891e2040d4bffff */
        H3: string;
        /** @enum {string} */
        CriterionId: "commute" | "transit" | "active" | "green" | "education" | "family" | "safety" | "price" | "shops" | "health" | "environment" | "leisure" | "accessibility";
        /** @enum {string} */
        ArchetypeId: "historic_core" | "urban_mix" | "student_buzz" | "estate_blocks" | "green_residential" | "family_suburb" | "quiet_outskirts" | "industrial_edge";
        I18nText: {
            pl: string;
            cs: string;
            en: string;
            ko: string;
        };
        LatLon: {
            lat: number;
            lon: number;
        };
        /** @description criterionId → 0–100 */
        CriterionScores: {
            [key: string]: number;
        };
        /** @description criterionId → importance level 0–5 */
        CriterionLevels: {
            [key: string]: components["schemas"]["Level"];
        };
        /**
         * @description real = A's data/processed; synthetic = engine dev data generated from config (no real data yet); fixture = static JSON
         * @enum {string}
         */
        DataSource: "real" | "synthetic" | "fixture";
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @example {
             *       "krakow": "2026-10-03T18:00:00Z",
             *       "praha": "2026-10-03T19:30:00Z"
             *     }
             */
            dataVersion: {
                [key: string]: string;
            };
            dataSource?: {
                [key: string]: components["schemas"]["DataSource"];
            };
            /** Format: date-time */
            builtAt: string;
        };
        City: {
            id: components["schemas"]["CityId"];
            name: components["schemas"]["I18nText"];
            /**
             * @example PL
             * @example CZ
             */
            country: string;
            defaultLang: components["schemas"]["Lang"];
            currency: components["schemas"]["Currency"];
            /** @description [lat, lon] */
            center: number[];
            zoom: number;
            /** @description [minLon, minLat, maxLon, maxLat] */
            bbox: number[];
            /** @enum {string} */
            priceMode: "buy" | "rent";
            /** @description criterionId → share 0–1 of the criterion's indicator weight that has real data in this city */
            coverage: {
                [key: string]: number;
            };
            dataVersion?: string;
            dataSource?: components["schemas"]["DataSource"];
        };
        Meta: {
            city: components["schemas"]["CityId"];
            dataVersion?: string;
            dataSource?: components["schemas"]["DataSource"];
            walkSpeedKmh?: number;
            levels: {
                level: components["schemas"]["Level"];
                weight: number;
                emoji: string;
                label: components["schemas"]["I18nText"];
            }[];
            criteria: components["schemas"]["CriterionMeta"][];
            personas: components["schemas"]["Persona"][];
            mustHaveCategories: {
                id: string;
                emoji: string;
                label: components["schemas"]["I18nText"];
                /** @description false if the category does not exist in this city or has no data */
                available: boolean;
            }[];
            archetypes: {
                id: components["schemas"]["ArchetypeId"];
                emoji: string;
            }[];
            modes: {
                id: components["schemas"]["Mode"];
                emoji: string;
                label: components["schemas"]["I18nText"];
            }[];
            price: {
                /**
                 * @example buy_per_m2
                 * @example rent_per_m2
                 */
                indicator: string;
                /** @enum {string} */
                mode: "buy" | "rent";
                currency: components["schemas"]["Currency"];
                unit: components["schemas"]["I18nText"];
                /** @enum {string} */
                filterField: "maxPricePerM2" | "maxRentPerM2";
                /** @enum {string} */
                budgetField: "total" | "monthlyRent";
                cityMedian?: number | null;
                min?: number | null;
                max?: number | null;
            };
            adminLevels: {
                district: components["schemas"]["AdminLevel"];
                neighborhood: components["schemas"]["AdminLevel"];
            };
            manifest: components["schemas"]["ManifestEntry"][];
        };
        AdminLevel: {
            label: components["schemas"]["I18nText"];
            count?: number | null;
        };
        CriterionMeta: {
            id: components["schemas"]["CriterionId"];
            emoji: string;
            label: components["schemas"]["I18nText"];
            /**
             * @description anchors = computed from request anchors (commute)
             * @enum {string|null}
             */
            runtime?: "anchors" | null;
            caveat?: components["schemas"]["I18nText"] | null;
            coverage: number;
            /** @description true when coverage < 0.5 — label "beta" in the UI */
            beta: boolean;
            /** @description manifest keys */
            sources: string[];
            indicators: components["schemas"]["IndicatorMeta"][];
        };
        IndicatorMeta: {
            /** @example stop_walk_min */
            id: string;
            /** @example transit.stop_walk_min */
            column: string;
            label: components["schemas"]["I18nText"];
            /**
             * @example min
             * @example dep_h
             * @example pct
             */
            unit: string;
            unitLabel: components["schemas"]["I18nText"];
            decimals?: number;
            norm: components["schemas"]["Norm"];
            weight: number;
            walkScaled?: boolean;
            crossCity: boolean;
            /** @enum {string} */
            priority?: "P0" | "P1" | "P2";
            /** @description share of habitable cells with a real (non-NaN) value */
            coverage: number;
            /** @description false if restricted to other cities or 0% coverage */
            available: boolean;
            sources?: string[];
        };
        Norm: {
            /** @enum {string} */
            type: "decay" | "percentile" | "inverse_percentile" | "threshold";
            good?: number;
            bad?: number;
            at?: number;
        };
        Persona: {
            /** @enum {string} */
            id: "student" | "working" | "parent" | "expecting" | "senior" | "expat" | "custom";
            emoji: string;
            label: components["schemas"]["I18nText"];
            weights: components["schemas"]["CriterionLevels"];
            /** @description column → weight override */
            indicatorWeights: {
                [key: string]: number;
            };
            walkFactor: number;
            suggestedAnchors: {
                id: string;
                label: components["schemas"]["I18nText"];
                mode: components["schemas"]["Mode"];
                level: components["schemas"]["Level"];
                /** @description pick the place from geocode results of this POI category (e.g. university) */
                poiCategory?: string;
            }[];
        };
        ManifestEntry: {
            key: string;
            url?: string | null;
            /** Format: date-time */
            fetchedAt?: string | null;
            licence?: string | null;
            rows?: number | null;
            /** @enum {string} */
            status: "ok" | "fallback" | "missing";
            note?: string | null;
        };
        Anchor: {
            /** @example a1 */
            id: string;
            label?: string;
            lat: number;
            lon: number;
            mode?: components["schemas"]["Mode"];
            /** @default 3 */
            level: number;
            /** @description hard filter for this anchor */
            maxMinutes?: number | null;
        };
        MustHave: {
            /**
             * @example metro_station
             * @example pharmacy
             */
            category: string;
            maxWalkMin: number;
        };
        Filters: {
            /** @description Kraków (buy), zł/m² */
            maxPricePerM2?: number | null;
            /** @description Praha (rent), Kč/m²/month */
            maxRentPerM2?: number | null;
            /** @description default maxMinutes for anchors that do not set their own */
            maxCommuteMinutes?: number | null;
            /** @default [] */
            mustHave: components["schemas"]["MustHave"][];
            maxNoiseDb?: number | null;
        };
        Budget: {
            /** @description Kraków: total purchase budget (PLN) */
            total?: number | null;
            /** @description Praha: monthly rent budget (CZK) */
            monthlyRent?: number | null;
        };
        ScoreRequest: {
            /**
             * @default 1
             * @constant
             */
            v: 1;
            lang?: components["schemas"]["Lang"];
            /** @description persona id; drives indicatorWeights and walkFactor */
            persona?: string | null;
            weights: components["schemas"]["CriterionLevels"];
            /** @description optional column → weight override on top of the persona */
            indicatorWeights?: {
                [key: string]: number;
            };
            /** @default [] */
            anchors: components["schemas"]["Anchor"][];
            filters?: components["schemas"]["Filters"];
            budget?: components["schemas"]["Budget"];
            /**
             * @default hex
             * @enum {string}
             */
            aggregate: "hex" | "district" | "neighborhood";
            /** @default 20 */
            limit: number;
            /**
             * @description false → cells: [] (smaller payload)
             * @default true
             */
            includeCells: boolean;
            /** @description what `top` is ordered by: null = match %, a CriterionId = that criterion's score, "anchor:<id>" = shortest travel time to that anchor; unknown values rank by match %. `score` stays the match % */
            rankBy?: string | null;
            /** @description aggregate=hex only: restrict `top` to the cells of this district id */
            district?: string | null;
        };
        /** @description [h3, score 0–100, passes 0|1]. passes = habitable AND all hard filters pass. */
        CellTuple: [
            components["schemas"]["H3"],
            number,
            0 | 1
        ];
        Explanation: {
            criterion: components["schemas"]["CriterionId"];
            /** @description column, e.g. transit.stop_walk_min; null for commute */
            indicator?: string | null;
            /** @description raw value behind the sentence */
            value: number;
            unit?: string;
            /** @example Metro/vlak 6 min pěšky */
            text: string;
        };
        AnchorTime: {
            id: string;
            label?: string | null;
            /** @description null = unreachable within 120 min */
            minutes: number | null;
            mode: components["schemas"]["Mode"];
        };
        PriceInfo: {
            indicator: string;
            value: number | null;
            /**
             * @example Kč/m²/měs.
             * @example zł/m²
             */
            unit: string;
            currency: components["schemas"]["Currency"];
            imputed?: boolean;
        };
        ArchetypeRef: {
            id: components["schemas"]["ArchetypeId"];
            p: number;
        };
        PlaceRef: {
            id: string;
            name: string;
        };
        RankedPlace: {
            /** @description h3 for kind=hex, admin id otherwise */
            id: string;
            /** @enum {string} */
            kind: "hex" | "district" | "neighborhood";
            rank: number;
            /** @description match %; aggregates: population-weighted mean over all habitable cells */
            score: number;
            /** @description neighbourhood name for hex, admin name otherwise */
            name: string;
            district?: components["schemas"]["PlaceRef"] | null;
            centroid: components["schemas"]["LatLon"];
            criteria: components["schemas"]["CriterionScores"];
            highlights: components["schemas"]["Explanation"][];
            warnings: components["schemas"]["Explanation"][];
            anchors: components["schemas"]["AnchorTime"][];
            price?: components["schemas"]["PriceInfo"] | null;
            budgetM2?: number | null;
            /** @example Za váš rozpočet ~55 m² */
            budgetText?: string | null;
            archetype?: components["schemas"]["ArchetypeRef"] | null;
            /** @description columns whose value was imputed with the city median */
            imputed: string[];
            passes: boolean;
            /** @description aggregates only: share of habitable cells that pass */
            sharePassing?: number | null;
            /** @description aggregates only */
            cellCount?: number | null;
            populationEst?: number | null;
        };
        RelaxHint: {
            /** @description price | noise | commute:<anchorId> | mustHave:<category> */
            filter: string;
            passingAfter: number;
            text: string;
        };
        ScoreResponse: {
            city: components["schemas"]["CityId"];
            currency: components["schemas"]["Currency"];
            lang: components["schemas"]["Lang"];
            computeMs: number;
            /** @enum {string} */
            aggregate: "hex" | "district" | "neighborhood";
            count: {
                cells: number;
                habitable: number;
                passing: number;
            };
            cells: components["schemas"]["CellTuple"][];
            top: components["schemas"]["RankedPlace"][];
            relaxHint: components["schemas"]["RelaxHint"] | null;
            /** @description level>0 but no data in this city (or commute without anchors) */
            excludedCriteria: components["schemas"]["CriterionId"][];
            weightsUsed: components["schemas"]["CriterionLevels"];
            cityMedian: components["schemas"]["CriterionScores"];
        };
        IndicatorValue: {
            criterion: components["schemas"]["CriterionId"];
            indicator: string;
            column: string;
            /** @description raw value; null when no data (imputed) */
            value: number | null;
            unit: string;
            score: number;
            /** @description effective weight for the current persona */
            weight?: number;
            cityMedianValue?: number | null;
            imputed: boolean;
            /** @description explanation sentence with the raw value */
            text?: string | null;
        };
        NearestPoi: {
            category: string;
            name?: string | null;
            lat: number;
            lon: number;
            walkMin: number;
        };
        ArchetypeDetail: components["schemas"]["ArchetypeRef"] & {
            /** @description archetypeId → probability */
            probs?: {
                [key: string]: number;
            };
        };
        Place: {
            id: components["schemas"]["H3"];
            /** @enum {string} */
            kind: "hex";
            city: components["schemas"]["CityId"];
            lang?: components["schemas"]["Lang"];
            centroid: components["schemas"]["LatLon"];
            name: string;
            neighborhood?: string | null;
            district: components["schemas"]["PlaceRef"] | null;
            habitable: boolean;
            populationEst?: number | null;
            score?: number | null;
            passes?: boolean | null;
            criteria: components["schemas"]["CriterionScores"];
            cityMedian: components["schemas"]["CriterionScores"];
            indicators: components["schemas"]["IndicatorValue"][];
            nearest: components["schemas"]["NearestPoi"][];
            anchors: components["schemas"]["AnchorTime"][];
            price?: components["schemas"]["PriceInfo"] | null;
            budgetM2?: number | null;
            budgetText?: string | null;
            archetype?: components["schemas"]["ArchetypeDetail"] | null;
            highlights?: components["schemas"]["Explanation"][];
            warnings?: components["schemas"]["Explanation"][];
        };
        CommuteResponse: {
            city: components["schemas"]["CityId"];
            /** @description res-8 H3 cell used as the destination */
            anchorCell: string;
            mode: components["schemas"]["Mode"];
            /** @constant */
            maxMinutes: 120;
            /** @description [res-9 h3, minutes] */
            cells: [
                components["schemas"]["H3"],
                number
            ][];
            computeMs?: number;
        };
        DistrictList: {
            city: components["schemas"]["CityId"];
            /** @enum {string} */
            level: "district" | "neighborhood";
            items: {
                id: string;
                name: string;
                centroid: components["schemas"]["LatLon"];
                cellCount: number;
                habitableCount?: number;
                populationEst?: number | null;
            }[];
        };
        SimilarPlace: {
            id: string;
            /** @enum {string} */
            kind: "hex" | "district";
            name: string;
            district?: components["schemas"]["PlaceRef"] | null;
            centroid: components["schemas"]["LatLon"];
            similarity: number;
            archetype?: components["schemas"]["ArchetypeRef"] | null;
            /** @description criteria where both places are strong */
            sharedTraits?: components["schemas"]["CriterionId"][];
        };
        SimilarResponse: {
            city: components["schemas"]["CityId"];
            from: components["schemas"]["H3"];
            items: components["schemas"]["SimilarPlace"][];
        };
        TwinsResponse: {
            from: {
                city: components["schemas"]["CityId"];
                id: string;
                /** @enum {string} */
                kind: "hex" | "district";
                name: string;
                district?: components["schemas"]["PlaceRef"] | null;
                centroid: components["schemas"]["LatLon"];
                archetype?: components["schemas"]["ArchetypeRef"] | null;
            };
            to: components["schemas"]["CityId"];
            items: components["schemas"]["SimilarPlace"][];
        };
        PrefPairs: {
            city: components["schemas"]["CityId"];
            pairs: {
                id: string;
                a: components["schemas"]["CriterionScores"];
                b: components["schemas"]["CriterionScores"];
            }[];
        };
        PrefFitRequest: {
            choices: {
                a: components["schemas"]["CriterionScores"];
                b: components["schemas"]["CriterionScores"];
                /** @enum {string} */
                choice: "a" | "b";
            }[];
        };
        PrefFitResponse: {
            weights: components["schemas"]["CriterionLevels"];
            confidence?: number;
        };
        GeocodeResponse: {
            query: string;
            items: {
                label: string;
                sublabel?: string | null;
                /** @enum {string} */
                kind: "address" | "poi" | "place" | "district";
                /** @description POI category when kind=poi (e.g. university) */
                category?: string | null;
                lat: number;
                lon: number;
                h3?: string | null;
                /** @enum {string} */
                source: "local" | "photon";
            }[];
        };
        LiveAir: {
            city: components["schemas"]["CityId"];
            /** @enum {string} */
            status: "ok" | "stale" | "unavailable";
            /**
             * @example GIOŚ
             * @example ČHMÚ
             * @example Golemio
             */
            source: string;
            station?: {
                id: string;
                name: string;
                lat: number;
                lon: number;
                distanceKm: number;
            } | null;
            /** @description 0 very good … 5 very bad (labels: texts.airLevel in indicators.yaml) */
            level?: number | null;
            /** @description µg/m³ */
            pollutants?: {
                pm25?: number | null;
                pm10?: number | null;
                no2?: number | null;
                o3?: number | null;
            };
            /** Format: date-time */
            measuredAt?: string | null;
            /** Format: date-time */
            fetchedAt: string;
            cacheTtlS?: number;
        };
        LiveDepartures: {
            city: components["schemas"]["CityId"];
            stopId: string;
            stopName?: string | null;
            /** @enum {string} */
            status: "ok" | "stale" | "unavailable";
            source?: string;
            departures: {
                line: string;
                headsign: string;
                /** @enum {string|null} */
                mode?: "tram" | "bus" | "metro" | "train" | "ferry" | null;
                /** Format: date-time */
                scheduled: string;
                /** Format: date-time */
                predicted?: string | null;
                delayMin?: number | null;
            }[];
            /** Format: date-time */
            fetchedAt: string;
        };
        /**
         * @description engine/export/criteria_scores_{city}.json — for VITE_STATIC_FALLBACK=1. The web app computes
         *     M = Σ W(level_c)·S_c / Σ W(level_c) over the criteria present (commute is absent).
         *     Persona indicator tweaks are pre-applied per persona in `byPersona`.
         */
        StaticCriteriaScores: {
            city: components["schemas"]["CityId"];
            dataVersion: string;
            /** Format: date-time */
            generatedAt: string;
            /** @description column order of the score arrays */
            criteria: components["schemas"]["CriterionId"][];
            /** @description level → weight */
            levels: {
                [key: string]: number;
            };
            /** @description [h3, habitable 0|1, ...scores in `criteria` order (null = no data)] for persona custom */
            cells: unknown[][];
            /** @description personaId → scores rows in the same order as `cells` (without h3/habitable) */
            byPersona?: {
                [key: string]: unknown[][];
            };
            cityMedian?: components["schemas"]["CriterionScores"];
        };
    };
    responses: {
        /** @description Unknown city, cell or district */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        City: components["schemas"]["CityId"];
        /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
        Lang: components["schemas"]["Lang"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listCities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: {
                /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getGrid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    score: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    getPlace: {
        parameters: {
            query?: {
                /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
                lang?: components["parameters"]["Lang"];
                /**
                 * @description base64url (no padding) of the JSON of a ScoreRequest (persona, weights, anchors, filters, budget).
                 *     Without it the place is scored with the persona "custom" defaults and no anchors.
                 */
                state?: string;
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
                h3: components["schemas"]["H3"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCommute: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                mode?: components["schemas"]["Mode"];
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuteResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    listDistricts: {
        parameters: {
            query?: {
                level?: "district" | "neighborhood";
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSimilar: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
                h3: components["schemas"]["H3"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTwins: {
        parameters: {
            query: {
                from: components["schemas"]["CityId"];
                to: components["schemas"]["CityId"];
                h3?: components["schemas"]["H3"];
                district?: string;
                limit?: number;
                /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    geocode: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                /** @description Language of server-rendered sentences. Defaults to the city's defaultLang. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLiveAir: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveAir"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLiveDepartures: {
        parameters: {
            query: {
                stopId: string;
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDepartures"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPrefPairs: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path: {
                city: components["parameters"]["City"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefPairs"];
                };
            };
        };
    };
    fitPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrefFitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefFitResponse"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
}

// ───── Friendly aliases (appended by contracts/tools/gen-types.sh) ─────
type S = components["schemas"];
export type AdminLevel = S["AdminLevel"];
export type Anchor = S["Anchor"];
export type AnchorTime = S["AnchorTime"];
export type ArchetypeDetail = S["ArchetypeDetail"];
export type ArchetypeId = S["ArchetypeId"];
export type ArchetypeRef = S["ArchetypeRef"];
export type Budget = S["Budget"];
export type CellTuple = S["CellTuple"];
export type City = S["City"];
export type CityId = S["CityId"];
export type CommuteResponse = S["CommuteResponse"];
export type CriterionId = S["CriterionId"];
export type CriterionLevels = S["CriterionLevels"];
export type CriterionMeta = S["CriterionMeta"];
export type CriterionScores = S["CriterionScores"];
export type Currency = S["Currency"];
export type DataSource = S["DataSource"];
export type DistrictList = S["DistrictList"];
export type Error = S["Error"];
export type Explanation = S["Explanation"];
export type Filters = S["Filters"];
export type GeocodeResponse = S["GeocodeResponse"];
export type H3 = S["H3"];
export type Health = S["Health"];
export type I18nText = S["I18nText"];
export type IndicatorMeta = S["IndicatorMeta"];
export type IndicatorValue = S["IndicatorValue"];
export type Lang = S["Lang"];
export type LatLon = S["LatLon"];
export type Level = S["Level"];
export type LiveAir = S["LiveAir"];
export type LiveDepartures = S["LiveDepartures"];
export type ManifestEntry = S["ManifestEntry"];
export type Meta = S["Meta"];
export type Mode = S["Mode"];
export type MustHave = S["MustHave"];
export type NearestPoi = S["NearestPoi"];
export type Norm = S["Norm"];
export type Persona = S["Persona"];
export type Place = S["Place"];
export type PlaceRef = S["PlaceRef"];
export type PrefFitRequest = S["PrefFitRequest"];
export type PrefFitResponse = S["PrefFitResponse"];
export type PrefPairs = S["PrefPairs"];
export type PriceInfo = S["PriceInfo"];
export type RankedPlace = S["RankedPlace"];
export type RelaxHint = S["RelaxHint"];
export type ScoreRequest = S["ScoreRequest"];
export type ScoreResponse = S["ScoreResponse"];
export type SimilarPlace = S["SimilarPlace"];
export type SimilarResponse = S["SimilarResponse"];
export type StaticCriteriaScores = S["StaticCriteriaScores"];
export type TwinsResponse = S["TwinsResponse"];
